name: EncExp
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - scikit-learn
  - pytest
  - tqdm
  - yaml
  - jupyter
  - CompStats
  - microtc
  - encexp
  - evomsa
  - wordcloud
  - matplotlib
  - tabulate
  - plotly
  - pip:
    - pandas
    - seaborn