# Recursos regionalizados para el procesamiento autom谩tico de datos de redes sociales

## Sobre esta charla
Tellez, E. S., Moctezuma, D., Miranda, S., Graff, M., & Ruiz, G. (2023). Regionalized models for Spanish language variations based on Twitter. Language Resources and Evaluation, 1-31.

```bibtex 
@article{regionalized2023,
  title={Regionalized models for Spanish language variations based on Twitter},
  author={Tellez, Eric S and Moctezuma, Daniela and Miranda, Sabino and Graff, Mario and Ruiz, Guillermo},
  journal={Language Resources and Evaluation},
  pages={1--31},
  year={2023},
  publisher={Springer}
}
```

- [ArXiv](https://arxiv.org/abs/2110.06128) preprint.


## Aplicaciones de Procesamiento de Lenguaje Natural (1/2)
- **Miner铆a de opini贸n**
  - <span style="color: rgb(0, 0, 255);">positivo :) </span> ---  <span style="color: rgb(130, 130, 130);">neutro :| </span> --- <span style="color: rgb(255, 0, 0);">negativo :( </span>
- **An谩lisis de t贸picos**
- **Carga emotiva de un mensaje**: _enojo, anticipaci贸n, disgusto, miedo, gozo, tristeza, sorpresa, confianza_.
- **Identificaci贸n de humor**
- **Identificaci贸n de lenguaje de odio**
- Etc.

## Aplicaciones de Procesamiento de Lenguaje Natural (2/2) {style='font-size: 80%;'}
- **Predicci贸n indicadores socio-demogr谩ficos de usuarios de redes**, e.g., edad, sexo, lugar de procedencia, ocupaci贸n
- **Identificaci贸n de autor铆a**: 驴qui茅nes escriben?, 驴c贸mo escriben?, 驴sobre qu茅 escriben?
- **Entender como se comportan usuarios**, 驴qu茅 desean?, 驴por qu茅?
- **Medici贸n de discurso de odio en redes sociales**, e.g., xenofobia, racismo, misoginia, cyberbulling.
- **Identificaci贸n de posibles trastornos mentales**, e.g., ansiedad, depresi贸n, adicciones.
- **Aplicaciones** a seguridad, salud, pol铆ticas p煤blicas, econom铆a y finanzas.

## Algunos retos

- Escritos informales: muchos errores, onomatopeya, importaci贸n de t茅rminos, variaciones regionales, emojis, entre muchos otros.
- Contextos cortos, conocimiento del mundo.
- Negaci贸n, sarcasmo, iron铆a, humor.
- Sem谩ntica.
- Recursos ling眉铆sticos reducidos para lenguajes diferentes del ingl茅s.
- Multimedios.

## Regionalizaci贸n
::: {style='background-color: rgb(200,250,250);'}
Todo lo anterior puede regionalizarse, ya que un mismo lenguaje puede usarse de manera diferente en diferentes regiones.
:::

::: {style='background-color: rgb(250,200,250);'}
Para tareas d贸nde haya una fuerte carga cultural o de idiosincrasia el uso de recursos regionalizados es provechoso.
:::

## Regionalizaci贸n como herramienta
Entender las **variaciones del lenguaje** en las redes sociales es primordial ya que los mensajes suelen ser **informales**, y es com煤n que los usuarios solo quieran ser le铆dos por su _c铆rculo_ de personas cercanas.

# 驴C贸mo se ven los mensajes en diferentes regiones?

## Espa帽a 
::: {style='background-color: red; color: yellow;'}
- me dais ascooooikiiikioooooooooooooooooooooooooo
- kina 帽efla
- ns cmo s exribe
- o indeciso, nse ya x dnde cogerte colega
- q os follennjajabya quisieran
- en el metro q voy esta potando uno
- _USR 癸 pero por qu茅 churra
:::

## Argentina 
::: {style='background-color: rgb(117,170,219); color: white;'}
- pofr suerxte m8铆s amigo mo son psic贸patassa
- pal pinnngooo
- _USR estos rompen todo! y la esposa del chorro me tir贸 en la cara q era planera, 5 hijos tiene. me grita: vos segu铆 alquilando! dec铆 q no la agarro de los pelos x mi hijo q no le gusta el bardo.
- y dsp se comi贸 un asado, moooy booenoぃ
- mi hno se pone re denso no lo banco
:::

## M茅xico 拆
::: {style='background-color: lightgreen; color: red;'}
- _USR ahora si! #achingarasumadre nefasto, corrupto y ratero, por mucho eres el peor alcalde que ha tenido _USR 
- ya me ando echando la primera ca** del a帽o
- _USR ac谩 ya andaban con "la chica que so帽茅"
- _USR 驴no se te olvid贸 ponerte calzones rojos hoy, verdad?
- un minuto de silencio por los que se estan reventando los dedos y las manos con los cohetes !!!
:::

{{< include _1corpus.qmd >}}
{{< include _2lexicos.qmd >}}
{{< include _3semanticos.qmd >}}
{{< include _4emoji15.qmd >}}
{{< include _5modelos-lenguaje.qmd >}}
{{< include _6conclusiones.qmd >}}